theme: jekyll-theme-cayman
title: David Fernández
description: As to methods, there may be a million and then some, but principles are few. The man who grasps principles can successfully select his own methods. - Ralph Waldo Emerson